### ISSUE TITLE
Document how to manage timeout

### ISSUE THREAD

**Issue by Duaner** [prismicio/prismic-client#129]
The release notes mention now the support for a timeout in prismic-javascript v2.6.0 and up. 

Could you document how to proceed please and can you advise whether we can send a timeout in the request to the cdn or when using the api object?

Thanks

**Comment by haletothewood** [comment]
Just going to add my ➕  to this issue. This would be super helpful for us as we are currently using AbortController and trying to support IE11 so that's super tricky.

**Comment by lihbr** [comment]
@angeloashmore maybe this can be interesting in v6 examples? Feel free to close if not/handled~

**Comment by lihbr** [comment]
@angeloashmore any thought?

**Comment by lihbr** [comment]
Added as an example~

https://github.com/prismicio/prismic-client/tree/master/examples/custom-timeout
