### ISSUE TITLE
Missing strict: true in tsconfig.json

### ISSUE THREAD

**Issue by horttanainen** [prismicio/prismic-client#141]
https://www.typescriptlang.org/tsconfig#strict

> The strict flag enables a wide range of type checking behavior that results in stronger guarantees of program correctness. Turning this on is equivalent to enabling all of the strict mode family options, which are outlined below. You can then turn off individual strict mode family checks as needed.

**Comment by lihbr** [comment]
Hey, as stated here: https://github.com/prismicio/prismic-javascript/issues/27#issuecomment-833459653 first-class TypeScript support is being added in the next version of this kit ☺️

**Comment by horttanainen** [comment]
Wonderful news! Thank you very much!

**Comment by lihbr** [comment]
Fixed in v6 🎉 Thank you for your contribution!

https://prismic.io/docs/technical-reference/prismicio-client?version=v6
