### ISSUE TITLE
Missing `isBroken` property into Document types

### ISSUE THREAD

**Issue by jevillard** [prismicio/prismic-client#144]
Add `isBroken` property into Document types for link resolver

```js
export interface Document {
    // ...
   isBroken?: boolean;
}
```
What do you thing ?

**Comment by lihbr** [comment]
Hey, as stated here: https://github.com/prismicio/prismic-javascript/issues/27#issuecomment-833459653 first-class TypeScript support is being added in the next version of this kit ☺️

**Comment by lihbr** [comment]
Hey @jevillard, I'm happy to announce we just released in beta [@prismicio/client](https://prismic.io/docs/technical-reference/prismicio-client?version=v6&utm_campaign=devexp&utm_source=github&utm_medium=core-beta-release) and [@prismicio/helpers](https://prismic.io/docs/technical-reference/prismicio-helpers?utm_campaign=devexp&utm_source=github&utm_medium=core-beta-release) (the new `prismic-dom`). Stable release is scheduled for November!

Those two packages now come with first-class TypeScript support so I figured out you'd be interested! [You can read more about how to give them a try here](https://prismic.io/blog/new-core-development-kits-now-in-beta?utm_campaign=devexp&utm_source=github&utm_medium=core-beta-release), your feedback is also very much appreciated~

Cheers!

**Comment by lihbr** [comment]
Fixed in v6 🎉 Thank you for your contribution!

https://prismic.io/docs/technical-reference/prismicio-client?version=v6

If you're still experiencing the issue with the new kit, feel free to reopen!
