### ISSUE TITLE
Prismic Javascript documention example does not work

### ISSUE THREAD

**Issue by neilmispelaar** [prismicio/prismic-client#154]
Hello,

As I was starting out a new project I noticed that the JavaScript example documentation contains sample code that throws an error. Below I've included the URL of the page that has the offending code, screenshots showing the error, and then further below sample code that does work. 

## Non functioning code example

URL: https://prismic.io/docs/technologies/integrating-with-an-existing-project-javascript

<img width="769" alt="Screen Shot 2021-02-06 at 3 31 46 PM" src="https://user-images.githubusercontent.com/9325038/107129020-6f7d6400-6890-11eb-94e4-808f0e76f571.png">

## Error

Here is the error that is being thrown: 

<img width="523" alt="Screen Shot 2021-02-06 at 3 33 15 PM" src="https://user-images.githubusercontent.com/9325038/107129044-a5224d00-6890-11eb-8887-2183202056d0.png">

## Working code example

The following code sample addresses the error shown above. (In the working code below I removed the `req` parameter, but you can put it back in and it works just fine. 

```
Prismic.client(apiEndpoint).query("")
      .then(function(response) {
        // response is the response object, response.results holds the documents
        console.log("Documents", response.results);
      }, function(err) {
      console.log("Something went wrong: ", err);
    });
```

**Comment by lihbr** [comment]
Documentation has been updated and revamped, thank you for your contribution 🙏
