### ISSUE TITLE
Doesn't work in cloudflare workers

### ISSUE THREAD

**Issue by Munter** [prismicio/prismic-client#158]
This library uses [cross-fetch](https://github.com/lquixada/cross-fetch) to polyfill fetch in the environments it runs in.

However, cross-fetch is not a proper polyfill. It replaces the native `fetch` with a polyfill based on `XMLHttpRequest` no whether `fetch` or `XMLHttpRequest` exist or not.

In Cloudflare workers you are limited to a web worker context, which has a very limited subset of javascript API available. In this environment you have `fetch`, but not `XMLHttpRequest`. So cross-fetch breaks the environment by clobbering the native `fetch` with a version that throws because `XMLHttpRequest` doesn't exist.

The same thing happens if I try to run the prismic client in a web worker or a serviceworker.

See also https://github.com/lquixada/cross-fetch/issues/69

**Comment by lihbr** [comment]
Hey @Munter, thanks for opening an issue, that's an interesting one!

We'll have a look at it, in the meantime, I can suggest you having a look at [ts-prismic](https://github.com/angeloashmore/ts-prismic) which is a lower level Prismic client that allows you to pick your query library.

**Comment by lihbr** [comment]
Hey @Munter, just letting you know we published @prismicio/client v6 in alpha, allowing you to provide your own fetcher function 🎉

While not documented yet the new kit has a very similar usage and comes with built-in tsdoc and an examples folder to already help you integrate with it ☺️

https://github.com/prismicio/prismic-javascript/tree/aa/v6/examples

https://github.com/prismicio/prismic-javascript/blob/3dfba0f4fb013421db58217cb02a810dab2b5fcc/src/client.ts#L145-L148

**Comment by lihbr** [comment]
Fixed in v6 🎉 Thank you for your contribution!

https://prismic.io/docs/technical-reference/prismicio-client?version=v6

If you're still experiencing the issue with the new kit, feel free to reopen!
