### ISSUE TITLE
Consider removing cross-fetch

### ISSUE THREAD

**Issue by Bram-Zijp** [prismicio/prismic-client#161]
I don't personally dig it to see a polyfilled fetch library I don't intend on using myself in my bundle.

Instead of including a library that includes a server side way to fetch, rely on a developer to make fetch globally available. One could use something like webpack or by specifying it global at root level e.g. `global.fetch = require('node-fetch')`

**Comment by lihbr** [comment]
Hey @Bram-Zijp, thanks for opening an issue! That's indeed something we'll consider when working on the next major of this kit!

**Comment by lihbr** [comment]
This had been implemented as part of v6 🎉

https://github.com/prismicio/prismic-javascript/blob/3dfba0f4fb013421db58217cb02a810dab2b5fcc/src/client.ts#L145-L148

**Comment by lihbr** [comment]
Fixed in v6 🎉 Thank you for your contribution!

https://prismic.io/docs/technical-reference/prismicio-client?version=v6
