### ISSUE TITLE
Enforce CDN endpoint

### ISSUE THREAD

**Issue by srenault** [prismicio/prismic-client#178]
We should enforce the use of CDN api endpoint. 
Mainly because the CDN endpoint is replicated over several regions and you gain performance in term of response time.

**Comment by lihbr** [comment]
Hey Sébastien, with v6 that will be enforced with people getting their endpoints through this function: https://github.com/prismicio/prismic-javascript/blob/aa/v6/src/getEndpoint.ts ☺️

Aside from that we still have patterns allowing us to use the client with wroom.io for debugging purpose~

**Comment by lihbr** [comment]
Fixed in v6 🎉 Thank you for your contribution!

https://prismic.io/docs/technical-reference/prismicio-client?version=v6
