### ISSUE TITLE
Is there any plan to type slices or body on Document ?

### ISSUE THREAD

**Issue by asotog** [prismicio/prismic-client#185]
Just noticed, slices are loaded from the body field in the data property, but ts complains about the lack of type for it, is there any plan to fix this ?

Thanks in advance

**Comment by angeloashmore** [comment]
Hey @asotog, good observation!

Yes, there are plans to provide TypeScript types for a Document's fields, including its Slice Zone(s). The next version of `@prismicio/client`, currently in development, will include full support for TypeScript.

[`@prismicio/types`](https://github.com/prismicio/prismic-types), a sibiling package to provide TypeScript types, can be used to construct your own Document types including its fields. It is in its early stages of development, but feel free to check it out.

Documentation for these updates will be published when they are ready.

Let me know if you have any other questions!

(cc @lihbr)

**Comment by lihbr** [comment]
Fixed in v6 🎉 Thank you for your contribution!

https://prismic.io/docs/technical-reference/prismicio-client?version=v6
