### ISSUE TITLE
How to retrieve only uids with .query(v5) / getAll{...}(v6)

### ISSUE THREAD

**Issue by GrefriT** [prismicio/prismic-client#197]
Hi. Is it possible to somehow get just the UID using `params.fetch` or `params.graphQuery`? It would be cool to add the ability to pass something like `document.{AnyDocumentField(like uid, id, first_publication_date, etc.)}` to fetch / graphQuery. I need this for getStaticPaths in next.js. I would like to decrease the payload size and only return what is really needed, because it affects the build time

**Comment by angeloashmore** [comment]
Hi @GrefriT,

If you only want to fetch document metadata, including its UID, you can use the `fetch` parameter to exclude any data fields. You can set the `fetch` parameter to `${documentType}.uid` (the `.uid` part can be anything that isn't a data field name).

For example, this is what it looks like using the v6 beta:

```ts
import * as prismic from '@prismcio/client'

const endpoint = prismic.getEndpoint('my-repo')
const client = prismic.createClient(endpoint)

const documents = client.getAllByType('page', { fetch: 'page.uid' })
```

There is no way to only return the UID field. This should be handled by Next.js, however. If you are using `getStaticPaths`, only the return value is persisted. Your return value should only include a list of UID strings.

I hope that answers your question! I'm going to close this but feel free to reply here if you have further questions.

**Comment by GrefriT** [comment]
@angeloashmore  thanks for the answer. It just seems a little strange to me that using the graphql api you can only return the UID, but not using `fetch`. I tried to use graphql in my project, but using the client is much more convenient and simpler. Is it possible in the future to have something like an alternative to `_meta` from graphql in `params.graphQuery`?

**Comment by angeloashmore** [comment]
@GrefriT Good point. I think that highlights the difference between GraphQL and REST APIs (speaking generally). Querying for only what you need is a core part of GraphQL API.

REST APIs (at least Prismic's API at this time) differ in that the API itself must support its own way of providing a subset of fields. Prismic provides that through the `fetch` or `graphQuery` parameters, but they are limited to the fields within data. "Meta" fields cannot be filtered.

Including a `_meta` field like you're requesting sounds reasonable to me. Could you open a feature request on the Prismic community forum here? https://community.prismic.io/c/features/12
