### ISSUE TITLE
Eslint resolver ESM issue

### ISSUE THREAD

**Issue by sarunast** [prismicio/prismic-client#199]
I noticed issues with EsLint - resolver plugin issues. This is with version 6-beta4.

This error is returned by EsLint once the prismic is included in the file `import * as prismic from "@prismicio/client";
` 

```
Error: ENOENT: no such file or directory, scandir '/node_modules/@prismicio/client/esm/@prismicio'
Occurred while linting /src/client/api/prismic/prismic.ts:1
```

**Comment by angeloashmore** [comment]
Hi @sarunast, it looks like the process printing that error is trying to read `@prismicio/client` V5 (the `/esm/@prismicio/` directory does not exist in V6). If you are using V6, the error is correct in that the `esm` folder does not exist.

Could you try deleting `node_modules` and re-install your packages? Also, is there a way you could restart ESLint or whatever package is throwing that error?

**Comment by sarunast** [comment]
I will close it for now. Since I don't work on this at the moment so I can't really confirm the issue.
