### ISSUE TITLE
Warn user when API v2 is not detected

### ISSUE THREAD

**Issue by lihbr** [prismicio/prismic-client#200]
### Is your feature request related to a problem? Please describe.

Client works with API v1, this leads to errors happening later in the stack with them having misleading information regarding the source of the issue.

(from a user) For example, when trying to resolve a link (through `@prismicio/react@2`), the above is thrown when using API v1, which is not helpful regarding the source of the issue:
![image](https://user-images.githubusercontent.com/25330882/145222519-9307919d-d304-4813-818f-7b352851d41f.png)

### Describe the solution you'd like

Client could `console.warn` if v2 is not detected in the endpoint: https://github.com/prismicio/prismic-client/blob/v6/src/client.ts#L313

I don't really see use cases where this could be inconvenient 🤔

### Describe alternatives you've considered

/

### Additional context

Not 100% sure about it, but well, could help avoid that kind of error~

**Comment by angeloashmore** [comment]
Good idea. Should be simple enough to check for `/api/v2` in the endpoint pathname. We could make sure it only happens in development.

If someone uses a custom endpoint (e.g. through a proxy), I don't think we should do anything complex to detect API V1. In that case, I think we should just rely on documentation to state that all current JavaScript packages only support API V2.

**Comment by angeloashmore** [comment]
Added in #203. It can be published in the next release.
