### ISSUE TITLE
RFC: Integrate a Prismic client into GraphQL clients

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-client#202]
### Is your feature request related to a problem? Please describe.

Today, `@prismicio/client` v6 is designed only for REST API V2. Using the GraphQL API requires one of the following approaches:

- Use Apollo with `apollo-link-prismic` (in need of maintenance and requires using Apollo).
- Setup a custom GraphQL client with its own method to fetching refs and setting authorization headers.

Apollo is relatively heavy. Other solutions like urql or `graphql-request` may be more desirable.

Setting up a custom GraphQL client is complex since it requires deep understanding of Prismic refs.

### Describe the solution you'd like

`@prismicio/client` could provide a GraphQL-specific integration that makes it easy to support any GraphQL client that supports fetch and GET requests. This includes libraries like `@apollo/client`, `urql`, and `graphql-request`.

`@prismicio/client` would handle a GraphQL client's fetch requests by using its built-in `fetch` method (which may be user-provided) and building the necessary set of headers.

For the following examples, assume a file named `prismic.ts` is available that exports a client and its repository name.

```ts
import * as prismic from "@prismicio/client";

export const repositoryName = "your-repo-name";
const endpoint = prismic.getEndpoint(repositoryName);

export const client = prismic.createClient(endpoint, {
  accessToken: "your-access-token",
});
```

#### With Apollo

An Apollo client could be setup like this (note that it only relies on core Apollo packages and `@prismicio/client`):

```ts
import {
  ApolloClient,
  HttpLink,
  InMemoryCache,
} from "@apollo/client";
import * as prismic from "@prismicio/client";

import { client, repositoryName } from "./prismic";

const graphqlClient = new ApolloClient({
  link: new HttpLink({
    uri: prismic.getGraphQLEndpoint(repositoryName),
    fetch: client.graphqlFetch,
    useGETForQueries: true,
  }),
  cache: new InMemoryCache(),
});
```

#### With `graphql-request` (and SWR)

A basic `graphql-request` client could be setup like this:

```ts
import { GraphQLClient, gql } from "graphql-request";
import * as prismic from "@prismicio/client";

import { client, repositoryName } from "./prismic";

const graphqlClient = new GraphQLClient(
  prismic.getGraphQLEndpoint(repositoryName),
  {
    method: "get",
    fetch: client.graphqlFetch,
  }
);
```

In React, this client could be combined with SWR for loading/error/refetch handling:

```ts
import useSWR from "swr";
import { GraphQLClient, gql } from "graphql-request";
import * as prismic from "@prismicio/client";

import { client, repositoryName } from "./prismic";

const graphqlClient = new GraphQLClient(
  prismic.getGraphQLEndpoint(repositoryName),
  {
    method: "get",
    fetch: client.graphqlFetch,
  }
);

const fetcher = (query: string) => graphqlClient.request(query);

function App() {
  const { data, error, isValidating } = useSWR(
    gql`
      query {
        allPages {
          edges {
            node {
              _meta {
                uid
              }
            }
          }
        }
      }
    `,
    fetcher
  );

  // ...
}
```

### Describe alternatives you've considered

Alternatives have been described above:

- Use Apollo with `apollo-link-prismic` (in need of maintenance and requires using Apollo).
- Setup a custom GraphQL client with its own method to fetching refs and setting authorization headers.

Additional GraphQL client-specific integrations could be created (for example, `urql-exchange-prismic`). This may not scale well as tooling changes over time and new libraries are authored.

If we *do* decide to create client-specific integrations, they could be made minimally by using the `graphqlFetch()` method described in this RFC.

### Additional context

- **Current Prismic + GraphQL documentation**: https://prismic.io/docs/technologies/integrate-with-existing-js-project-graphql
- **apollo-link-prismic**: https://github.com/prismicio/apollo-link-prismic

**Comment by lihbr** [comment]
Can this be closed @angeloashmore? Are we missing something?

**Comment by angeloashmore** [comment]
Yes, this can be closed. `graphQLFetch()` and `getGraphQLEndpoint()` have been published. They will be documented when the official Prismic GraphQL docs are updated.
