### ISSUE TITLE
[RFC] Better error messaging for GraphQuery

### ISSUE THREAD

**Issue by phillysnow** [prismicio/prismic-client#209]
### Issue

When users currently do not correctly format a GraphQuery their queries simply fail.

### Solution

The [API browser for example](https://smallbydesign.prismic.io/api/v2/documents/search?ref=YedLOREAACoA6f28&q=%5B%5Bat(my.page.uid%2C+%22contact-us%22)%5D%5D&graphQuery=%7B%0Apage%7B%0A...pageFields%0Aslices%7B%0A...onform_section%7B%0Avariation%7B%0A...ondefault-slice%7B%0Aprimary%7B%0AformLink%7B%0A...onform%7B%0Aslices%7B%0A...onform_input%7B%0Avariation%7B%0A...ondefault-slice%7B%0Arepeat%7B%0A...primaryFields%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D#format=json) returns more specific error messaging:
```
  <body>
  
      <p>Unable to parse fetch query Invalid fetch parsing Exception.

A composite slice can only contains `primary` or `repeat` or both.</p>
    
  </body>
```

Could we pull this error messaging into the Client?

### Forum 
https://community.prismic.io/t/not-able-to-query-slice-machine-slices-with-graphquery/7030/24

**Comment by lihbr** [comment]
Related, but just a side note that non-CDN version returns HTML, while CDN version returns JSON (same content though):
- CDN: https://smallbydesign.cdn.prismic.io/api/v2/documents/search?ref=YedLOREAACoA6f28&q=%5B%5Bat(my.page.uid%2C+%22contact-us%22)%5D%5D&graphQuery=%7B%0Apage%7B%0A...pageFields%0Aslices%7B%0A...onform_section%7B%0Avariation%7B%0A...ondefault-slice%7B%0Aprimary%7B%0AformLink%7B%0A...onform%7B%0Aslices%7B%0A...onform_input%7B%0Avariation%7B%0A...ondefault-slice%7B%0Arepeat%7B%0A...primaryFields%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D#format=json
- Non-CDN: https://smallbydesign.prismic.io/api/v2/documents/search?ref=YedLOREAACoA6f28&q=%5B%5Bat(my.page.uid%2C+%22contact-us%22)%5D%5D&graphQuery=%7B%0Apage%7B%0A...pageFields%0Aslices%7B%0A...onform_section%7B%0Avariation%7B%0A...ondefault-slice%7B%0Aprimary%7B%0AformLink%7B%0A...onform%7B%0Aslices%7B%0A...onform_input%7B%0Avariation%7B%0A...ondefault-slice%7B%0Arepeat%7B%0A...primaryFields%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D#format=json

**Comment by phillysnow** [comment]
Oh lord, that's nice.

**Comment by angeloashmore** [comment]
Hey @phillysnow, the v6 client handles this by returning a `ParsingError`. The helpfulness of the error is limited by the API response ("A composite slice can only contains `primary` or `repeat` or both" isn't exactly the most helpful message).

When making the same query as linked in the issue and above, the client will throw the following error (`graphQuery` is the linked GraphQuery string saved in a variable). It is the same error displayed by the API browser.

```
> client.getByUID('page', 'contact-us', { graphQuery }).then(x => console.log(x)).catch(x => console.log(x))
> ParsingError: Unable to parse fetch query Invalid fetch parsing Exception.

A composite slice can only contains `primary` or `repeat` or both.
    at Client.fetch (/Users/angeloashmore/projects/prismic/prismic-client/dist/index.cjs:524:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.getFirst (/Users/angeloashmore/projects/prismic/prismic-client/dist/index.cjs:264:20)
    at async Client.getByUID (/Users/angeloashmore/projects/prismic/prismic-client/dist/index.cjs:299:12) {
  url: 'https://smallbydesign.cdn.prismic.io/api/v2/documents/search?q=%5B%5Bat%28document.type%2C+%22page%22%29%5D%5D&q=%5B%5Bat%28my.page.uid%2C+%22contact-us%22%29%5D%5D&graphQuery=%7B%0Apage%7B%0A...pageFields%0Aslices%7B%0A...onform_section%7B%0Avariation%7B%0A...ondefault-slice%7B%0Aprimary%7B%0AformLink%7B%0A...onform%7B%0Aslices%7B%0A...onform_input%7B%0Avariation%7B%0A...ondefault-slice%7B%0Arepeat%7B%0A...primaryFields%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D&ref=YedLOREAACoA6f28',
  response: {
    type: 'api_validation_error',
    message: 'Unable to parse fetch query Invalid fetch parsing Exception.\n' +
      '\n' +
      'A composite slice can only contains `primary` or `repeat` or both.'
  }
}
```

---

> Related, but just a side note that non-CDN version returns HTML, while CDN version returns JSON (same content though)

Huh, interesting! That seems like an API issue rather than something that should be handled in the client. What do you think @lihbr?

**Comment by phillysnow** [comment]
OK, so the client already returns this info, that's awesome. I agree, we could definitely speak with the dev team about making these error messages more helpful though.

**Comment by lihbr** [comment]
> Huh, interesting! That seems like an API issue rather than something that should be handled in the client. What do you think @lihbr?

OK, actually the non-CDN version returns HTML because accessed from a browser (user-agent based?) using tools like Insomnia it returns valid JSON. Definitely shouldn't be handled by the client.

**Comment by angeloashmore** [comment]
I'm going to close this since the client already handles this by throwing a `ParsingError`. If anyone has suggestions on improving this (considering the API limitations), please feel free to share. 🙂
