### ISSUE TITLE
Support for AbortController/signals

### ISSUE THREAD

**Issue by sarunast** [prismicio/prismic-client#214]
It would be great if the library methods would be cancelable. It should be possible since the library is using `fetch`. 

The use case. The user enters SPA website with a slow internet which makes a direct request to Prismic API. The user changes his mind (before the requests were finished) and navigates to another page within SPA. The requests will still finish even though the user is on another page and there is no way at the moment to cancel them.

Example of canceled `fetch` with AbortController:
https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

**Comment by angeloashmore** [comment]
Hey @sarunast, great suggestion! Your use case totally makes sense and is something the client should support.

I implemented this functionality in #221. It follows the `fetch()` implementation of passing an `AbortController`'s signal to a client's method.

Does this accomplish what you are looking for?

Before merging and publishing, I'd like to get @lihbr's review/opinion. Thanks for your patience! 🙂

**Comment by sarunast** [comment]
Yes, that's exactly what I had in mind. Thanks for iterating on it so quickly.

**Comment by angeloashmore** [comment]
Awesome! Glad to hear that.

This is published in `v6.2.0`. The `signal` param is not documented yet, but an example is provided in the PR here: https://github.com/prismicio/prismic-client/pull/221

A timeout-specific example is also available here: https://github.com/prismicio/prismic-client/tree/master/examples/custom-timeout

Thanks again @sarunast for the suggestion!
