### ISSUE TITLE
Get documents by tag queries expecting an array of tags but TypeScript expects a single string

### ISSUE THREAD

**Issue by arochadaniel** [prismicio/prismic-client#215]
### Versions

- @prismicio/client: 6.1.1
- node: 12
- Next.js: 12

### Steps to reproduce
I was trying to get all the documents by tags inside getStaticProps to categorize inside my app, but every time I invoked 
```
const tagPosts = await PrismicClient.getAllByTag("Clima");
```
The app would crash with the following error:
```
Error: [function at(..)] field 'document.tags' expected a [list] of 'string' literals  on line:1 col:21 in query '[[at(document.tags, "Clima")]]' [[at(document.tags, "Clima")]]
```

I managed to "fix" the issue by putting the tag inside an array like this:
```
const tagPosts = await PrismicClient.getAllByTag(["Clima"]);
```
But now I'm left with the TS error that the function expects a string, not an array, so I have to use `@ts-ignore`

### What is expected?
The TS type function declaration should expect an array of strings, or the function itself should receive the non-array string correctly.

### What is actually happening?
It throws when I use the correct types that TS expects, but works when is inside an array (like the error asks)

**Comment by angeloashmore** [comment]
Hey @arochadaniel, thanks for reporting this issue.

This is now fixed as of `v6.2.0` via #220. If you update, you should be able to revert your code to passing a string rather than an array.

If you're still having an issue, please let me know and I can take another look.

Thanks!
