### ISSUE TITLE
Unable to provide a boolean to predicates

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-client#229]
Predicates are typed to only accept `string`s and `number`s (and arrays of those) by default.

If a predicate refers to a Boolean field, however, a `boolean` value is needed.

See this Prismic Community thread for more details: https://community.prismic.io/t/typescript-error-when-using-booleans-in-predicates/9391

### Versions

- @prismicio/client: v6.4.1
- node: v14.18.1

### Reproduction

```ts
import { predicate } from '@prismicio/client'

predicate.at('my.blog_post.is_hidden', true)
// TypeScript complains that predicate.at() doesn't accept a boolean value in the second argument
```

### Steps to reproduce

Run the above code snippet.

### What is expected?

Predicates accept boolean values.

### What is actually happening?

The code runs correctly (i.e. it handles `booleans` in the final API URL), but TypeScript says it is invalid.

**Comment by lihbr** [comment]
Here you go, I also added date support: f15f6061bcaafaef4e0a775da6a1167344e830dd

**Comment by angeloashmore** [comment]
Awesome, that looks great!
