### ISSUE TITLE
Typescript error in 6.6.x version

### ISSUE THREAD

**Issue by pinktonio** [prismicio/prismic-client#255]
### Versions

-  @prismicio/client: 6.6.4
-  typescript": 4.6.2

### Reproduction

Version 6.6.x causes the following typescript errors in my project:

`node_modules/@prismicio/client/node_modules/@prismicio/helpers/dist/index.d.ts:386:2 - error TS1005: '?' expected. 386 }) ? {`

`node_modules/@prismicio/client/node_modules/@prismicio/helpers/dist/index.d.ts:396:2 - error TS1005: '?' expected. 396 }) ? Data_1 & {`

**Comment by lihbr** [comment]
Seems like a duplicate of: https://github.com/prismicio/prismic-helpers/issues/54

Are you able to update your TypeScript version?

**Comment by pinktonio** [comment]
@lihbr Oh thanks I didn't see that. Yes i'm able to update. That fixed my problem.

**Comment by lihbr** [comment]
No worries! It's awesome that sorted out the issue for you :)

We're working on our end to find a way to mitigate those "TypeScript breaking changes" type of thing in the future.
