### ISSUE TITLE
Support new `brokenRoute` parameter in types

### ISSUE THREAD

**Issue by lihbr** [prismicio/prismic-client#257]
### Is your feature request related to a problem? Please describe.

Following the recent route resolver update, a new `brokenRoute` API query parameter is available. It allows users to define a fallback URL that will be resolved for fields featuring a broken link. Typical use case would be `brokenRoute: "/404"` to make all broken links populated with a `/404` URL.

### Describe the solution you'd like

Support is technically already here, but is not typed.

Type should be `brokenRoute?: string`

### Describe alternatives you've considered

N/A

### Additional context

Internal thread: https://prismic-team.slack.com/archives/CB6AJT98F/p1660692486110229

**Comment by angeloashmore** [comment]
Implemented in #258 along with the new `uid` option, pending a review. 🙂
