### ISSUE TITLE
npm run build doesn't work

### ISSUE THREAD

**Issue by adbutterfield** [prismicio/prismic-client#262]
Hello!

I'm trying to debug what I think is a bug in @prismicio/client, but I can't build to test my changes...

### Versions

- @prismicio/client: 6.7.0
- node: 16.15.1

### Reproduction

run `npm run build`

<details open>
<summary>Additional Details</summary>
<br>

Here is the log I get:

> @prismicio/client@6.7.0 build

\> siroc build

ℹ Beginning build                                                                          @prismicio/client 16:36:12
✔ Built @prismicio/client      index.d.ts   5.0 kB                                         @prismicio/client 16:36:16

 ERROR  [PARSE_ERROR] Unexpected token (Note that you need plugins to import files that are not JavaScript)
at /Users/adam.a.butterfield/projects/myaxa-web/node_modules/@prismicio/client/src/index.ts:40:7

  at src/index.ts:40:7
  at error (node_modules/rollup/dist/shared/rollup.js:198:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:12560:16)
  at Module.tryParse (node_modules/rollup/dist/shared/rollup.js:12937:25)
  at Module.setSource (node_modules/rollup/dist/shared/rollup.js:12842:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/shared/rollup.js:22284:20)

 ERROR  [PARSE_ERROR] Unexpected token (Note that you need plugins to import files that are not JavaScript)
at /Users/adam.a.butterfield/projects/myaxa-web/node_modules/@prismicio/client/src/index.ts:40:7

  at src/index.ts:40:7
  at error (node_modules/rollup/dist/shared/rollup.js:198:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:12560:16)
  at Module.tryParse (node_modules/rollup/dist/shared/rollup.js:12937:25)
  at Module.setSource (node_modules/rollup/dist/shared/rollup.js:12842:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/shared/rollup.js:22284:20)

 ERROR  undefined                                                                                            16:36:16

 ERROR  undefined                                                                                            16:36:16

✔ Finished building in 4.0s                                                                @prismicio/client 16:36:16

For convenience, line 40 is:
```
export type { CreateClient, ClientConfig } from "./client";
```
Looks like it doesn't like "export type".
</details>

### Steps to reproduce

run `npm run build`

### What is expected?

Build not to fail.

### What is actually happening?

Build is failing...

**Comment by lihbr** [comment]
Hi there,

Looks like you're trying to build the package from your `node_modules` directory where not all dependencies are installed to build (develop) on `@prismicio/client` (namely looks like it's missing some TypeScript bits/plugins from the above)

Are you able to build it using the "regular" way?

```bash
git clone git@github.com:prismicio/prismic-client.git
cd prismic-client
npm install
npm run build
```

---

Happy to read more about what you think is a bug on `@prismicio/client` also :)

**Comment by adbutterfield** [comment]
That works! Thanks!!!

I'll open another issue when I've determined where the bug is.

**Comment by adbutterfield** [comment]
Follow up on the bug: Bug seems to be in node-fetch actually, where this: https://github.com/prismicio/prismic-client/blob/e7ab774be4e9d0379817e7ce7b87b3c041c64f01/src/client.ts#L1664 never resolves or throws, quite randomly.

**Comment by lihbr** [comment]
Interesting, `node-fetch` should be matching this interface though 🤔

https://github.com/node-fetch/node-fetch/blob/main/src/body.js#L147-L150

Happy to look more into it if you can provide a minimal reproduction :)

**Comment by adbutterfield** [comment]
I found a few issues in the node-fetch repo that smell like my issue: https://github.com/node-fetch/node-fetch/issues/137 https://github.com/node-fetch/node-fetch/issues/665
So next step is to figure out exactly why it's failing. Right not it seems quite random.
