### ISSUE TITLE
Published New Content Doesn't Appear In prismicClient.getById(id) response

### ISSUE THREAD

**Issue by Aid19801** [prismicio/prismic-client#264]
### Versions

- @prismicio/client:  6.7.1
- node: 10.16.3

### Reproduction
You can reproduce this by setting up an express server, an `app.post('/my-webhook'...` handler and then trying to retrieve the document with its updated content included.

### Steps to reproduce
- Setup Node server, using Express
- Add a webhook handler
- In Prismic's UI, add a webhook that tells your server when a new doc has been published.
- The webhook will pass it the doc's ID
- now call `prismicClient.getByID(docId)` and the content/changes you published in that document will not be there.

### What is expected?
I expect the changes to be visible within the response so i can re-post them elsewhere, render them to a client etc.

### What is actually happening?
The response comes through with the old state of the document.

My Code:

```
    app.post("/prismic-doc-published", async (req, res) => {
    
      const hasDocId =
        req.body.documents &&
        req.body.documents.length &&
        req.body.documents.length > 0;
        
         if (hasDocId) {
             const docId = req.body.documents[0]
             const doc = await prismicClient.getByID(docId)


          const n = doc.data.body[0].items.length - 1 // <-- index of most recent podcast episode added on Prismic's UI
          const specificEpisode = doc.data.body[0].items[i] // <-- specific episode's information (img, title, description, link)
          console.log("specificEpisode is ", specificEpisode) // <-- this is always coming through as the second most recent episode
    }
    
```

To get it to update and feed me the correct episode information I have to rebuild the node app, re-deploy and *then* it's the correct response.

Is this a cache setting in Prismic client? Or do i have to find some weird wonderful way of triggering a heroku build and deploy everytime i publish a new podcast episode?

Yours in hope! :) x

**Comment by lihbr** [comment]
Hey there, thanks for opening an issue.

Can you confirm the issue is still happening using [a supported version of Node](https://github.com/nodejs/release#release-schedule) (14 or greater)?

**Comment by lihbr** [comment]
Closing as stale. Feel free to reopen if you'd like to continue troubleshooting this potential issue :)
