### ISSUE TITLE
The client for prismic in version 3 seems to be slower

### ISSUE THREAD

**Issue by hlassiege** [prismicio/prismic-client#270]
### Versions

- @prismicio/client: 3.0.0-rc.2
- node: 16.17

### Reproduction

Both projects are here :

https://gitlab.com/maltcommunity/public/singapore-prototypes/-/tree/master/prismic-nuxt-2
https://gitlab.com/maltcommunity/public/singapore-prototypes/-/blob/master/prismic-nuxt-3

### Steps to reproduce
We encountered performance issues since our migration to Nuxt3 and we suspect the prismic module.

When running the projects above, we log the time on both version to query a prismic document

To reproduce, just checkout the projects, run npm install and then npm dev

### What is expected?
Time should be equivalent in both version

### What is actually happening?

With the version 3, the time is significatively slower

![image](https://user-images.githubusercontent.com/666123/205644086-9a02c618-e54b-44ed-bc85-1ea33f38ca19.png)

It's maybe related to nuxt (even if I doubt it), that's why there is a duplicate issue in the nuxt project 

https://github.com/nuxt-modules/prismic/issues/174

**Comment by lihbr** [comment]
Closing in favor of https://github.com/nuxt-modules/prismic/issues/174 as the issue seems more on the Nuxt side for now. Will reopen/come back here if needed.
