### ISSUE TITLE
Missing exports in requested module (skypack @prismicio/client)

### ISSUE THREAD

**Issue by DeiveLab** [prismicio/prismic-client#272]
### Versions

- @prismicio/client: cdn.skypack.dev/@prismicio/client package
- node: browser

### Steps to reproduce

1. Follow [the instructions for prismic setup on browser](https://prismic.io/docs/setup-vanilla-javascript)
2. After adding the script line `import * as prismic from 'https://cdn.skypack.dev/@prismicio/client'`, open the browser
3. The error _Uncaught SyntaxError: The requested module '/-/@prismicio/richtext@v2.1.2-xpg8EyWwrWOVukye9GlX/dist=es2019,mode=imports/optimized/@prismicio/richtext.js' does not provide an export named 'Element' (at asHTML-c72c6cce.js:1:48)_ should appear on the browser console.

### What is expected?

The import should complete gracefully and provide access to the prismic tools, allowing the client to fetch the page content

### What is actually happening?

Error on base skypack @prismic/client module import, breaking page functionality
![prismic-import-error](https://user-images.githubusercontent.com/68397740/208469741-1f180b8a-ac0a-4f6a-9b44-7b1f19359276.png)

**Comment by lihbr** [comment]
Hey there,

Thank you so much for creating an issue and sorry for the inconvenience.

I just released some updates fixing the dependency for Skypack. Once Skypack cache has updated its cache, it should work fine again (I just tested now, it seems already done), in the meantime, if you still have issues, it should work with those scripts instead:

```javascript
import * as prismic from 'https://cdn.skypack.dev/@prismicio/client@6.7.3'
import * as prismicH from 'https://cdn.skypack.dev/@prismicio/helpers@2.3.8'
```

Let us know if anything!
