### ISSUE TITLE
Change `LinkResolver`'s default return type to `string | null | undefined`

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-client#273]
### Is your feature request related to a problem? Please describe.

With the recent improvements to Route Resolver, Link Resolver can now be used as a way to override Route Resolver's URL. To do this, Link Resolver must return a nullish value to fallback to the Route Resolver's value.

`LinkResolver`'s return type can be configured via the `ReturnType` type parameter ([see source here](https://github.com/prismicio/prismic-client/blob/a3a66095dc62a3e4bf073f7b2d17c9758b20e93e/src/types/helpers.ts#L19-L21)), but it defaults to `string`. Defaulting to `string` requires overriding the return type anytime Link Resolver is used as a way to override Route Resolver since it will return a nullish value.

### Describe the solution you'd like

`LinkResolver`'s default return value should change from `string` to `string | null | undefined` to support nullish return values.

### Describe alternatives you've considered

`LinkResolver` can be configured to return nullish values using its type parameter, but this is unergonomic and feels like straying from best practices.

```
LinkResolver<string | null | undefined>
```

### Additional context

None

**Comment by lihbr** [comment]
Do we want to move on with that (I'm all for it), happy to work on it on v7

**Comment by angeloashmore** [comment]
Yes, let's do this!

**Comment by lihbr** [comment]
Addressed in [`3e1fc53` (#265)](https://github.com/prismicio/prismic-client/pull/265/commits/3e1fc53397e038dad1b1f8ecb78a63ac40477a94), didn't feel like it was worthy of a standalone PR, left context in the commit body :)
