### ISSUE TITLE
Handle createClient custom fetch function errors

### ISSUE THREAD

**Issue by cpatti97100** [prismicio/prismic-client#296]
### Versions

- @prismicio/client: 6.7.3
- node: v16.20.0

### Reproduction

```js
const client = prismic.createClient('some', {
  accessToken,
  fetch: async (url, options) => {
    try {
      const response = await pRetry(() => fetch(url, options), {
        retries: maxRetry,
        onFailedAttempt: async (error) => {
          logger.warn({
            error
          }, 'Retrying prismic client network request')

          await sleep(waitBetweenRetriesInMilliseconds)
        },
      })

      return response
    } catch (error) {
      logger.error({
        error
      }, 'Prismic client network request failed too many times')

      throw new Error('Prismic client network request failed too many times')
    }
  },
})

// further down the file, in some function

try {
  return client.dangerouslyGetAll({
      predicates: prismic.predicate.any('document.type', pageTypes),
      lang: locale,
      ...options,
    })
} catch (error) {
  console.debug('getDataPrismic 149')
}
```

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

Run the code above

### What is expected?

I expect that after I throw an error in my custom fetch function, eventually `dangerouslyGetAll` also rejects and I can see the `console.debug` output.

### What is actually happening?

The error is not handled in the prismicio client and the application crashes.

Possible point of intervention
https://github.com/prismicio/prismic-client/blob/master/src/client.ts#L1713

```
error - lib/getDataPrismic.js (53:12) @ Client.fetch [as fetchFn]
error - Error: Prismic client network request failed too many times
    at Client.fetch [as fetchFn] (webpack-internal:///./lib/getDataPrismic.js:79:19)
    at async Client.fetch (file:///someProject/node_modules/@prismicio/client/dist/client.js:385:17)
    at async Client.get (file:///someProject//node_modules/@prismicio/client/dist/client.js:96:12)
    at async Client.dangerouslyGetAll (file:///someProject//node_modules/@prismicio/client/dist/client.js:123:22)
    at async getSiteData (webpack-internal:///./lib/getDataPrismic.js:469:23)
    at async Promise.all (index 0)
    at async getStaticProps (webpack-internal:///./templates/SomePage.js:345:26) {
  page: '/some-page'
}
  51 |       logger.error({ error }, 'Prismic client network request failed too many times')
  52 | 
> 53 |       throw new Error('Prismic client network request failed too many times')
     |            ^
  54 |     }
  55 |   },
  56 | })
```

**Comment by lihbr** [comment]
Hey there, thanks for opening an issue!

I'm not able to reproduce it, unfortunately.

1. Can you confirm that I'm on a similar setup to you here? https://replit.com/@lihbr/prismicioclient296-1#index.js
2. Are you sure the error is thrown by this part of the code? On the stack trace you shared it appears it's coming from a `dangerouslyGetAll` call, not by a `getByUID` one.

**Comment by cpatti97100** [comment]
thank you so much Lucie, the error was indeed on my side, I just updated the actual running code snippet ⬆️ 

the line `return client.dangerouslyGetAll` would delegate the error handling to the calling function, effectively skipping the catch block below.

your replit was indeed essential for fixing the issue, thank you so much 🙏🏼
