### ISSUE TITLE
Ability to define the output location for the types output by codegen when using slicemachine

### ISSUE THREAD

**Issue by zeckdude** [prismicio/prismic-client#301]
### Is your feature request related to a problem? Please describe.
When I save custom types, `prismic-ts-codegen` outputs the types to `./prismicio-types.d.ts` automatically. I'd like to be able to configure the output location for that. 

### Describe the solution you'd like
Perhaps a property in the `slicemachine.config.json` file can tell you where that should be output.

### Describe alternatives you've considered
None

**Comment by angeloashmore** [comment]
Hi @zeckdude, thanks for the feature request! I'm going to move it over to the prismicio/slice-machine repository since that is where `@slicemachine/adapter-next` lives.
