### ISSUE TITLE
Migration guide is unavailable

### ISSUE THREAD

**Issue by brunosala** [prismicio/prismic-client#306]
https://prismic.io/docs/prismicio-client-v7-migration-guide

![image](https://github.com/prismicio/prismic-client/assets/39502786/01d7fe38-ef6a-4068-a077-f6ff51692f61)

**Comment by lihbr** [comment]
Hey there, thanks for contributing! We're having a small outage on our website. It should be up again in a few 🚀
Thanks for your patience~
