### ISSUE TITLE
Type error after update to v7.1.0

### ISSUE THREAD

**Issue by andre-lergier** [prismicio/prismic-client#309]
After updating form v7.0.1 to v7.1.0 I get a type error related to `first_publication_date` of `AllDocumentTypes`:
`Type 'AllDocumentTypes' does not satisfy the constraint 'PrismicDocument<Record<string, any>, string, string>'.ts(2344)`

### Steps to reproduce
I have a function to get all Prismic singleton data:
```ts
export const getAllSingletonData = async (
  client: Client<Content.AllDocumentTypes>
) => {
  const navigation = await client.getSingle('navigation');
  const settings = await client.getSingle('settings');

  return {
    navigation,
    settings,
  };
};
export type AllSingletonData = Awaited<ReturnType<typeof getAllSingletonData>>;
```

In page files I use the function in getStaticProps:
```ts
export async function getStaticProps({
  params,
  previewData,
}: GetStaticPropsContext) {
  const client = createClient({ previewData });
  const singletonData = await getAllSingletonData(client);
  const sliceZoneData: SliceZoneData = await getSliceZoneData(client);

  const uid =
    (Array.isArray(params?.uid)
      ? params?.uid[params?.uid.length - 1]
      : params?.uid) || 'home';
  const page = await client.getByUID('page', uid, {
    graphQuery: pageGraphQuery,
  });

  return {
    props: {
      params,
      page,
      singletonData,
      sliceZoneData,
    },
  };
}
```

### What is actually happening?
Until now, everything worked well.
Since the update I get the following error: 
```zsh
Type error: Type 'AllDocumentTypes' does not satisfy the constraint 'PrismicDocument<Record<string, any>, string, string>'.
  Type 'NavigationDocument<string>' is not assignable to type 'PrismicDocument<Record<string, any>, string, string>'.
    Types of property 'first_publication_date' are incompatible.
      Type 'string' is not assignable to type '`${number}-${number}-${number}T${number}:${number}:${number}+${number}`'.
```

### What is expected?
How can I fix this error? 
Do I have to change the type of the client parameter (`client: Client<Content.AllDocumentTypes>`) or is it a @prismicio/prismic-client problem?

I rebuild the types manually and triggered a type regeneration via editing a custom type in Slicemachine and save it to the file system.

### Versions

- @prismicio/client: v7.1.0
- node: v18.16.0

**Comment by lihbr** [comment]
Hey there, thanks for contributing!

Can you also share a dump of your `prismicio-types.d.ts` file (or alike), as well as your Slice Machine adapter version (`@slicemachine/adapter-*`) or your `prismic-ts-codegen` version if using it directly?

I think I know where this is coming from.

**Comment by lihbr** [comment]
OK, thanks! Can you try updating `@slicemachine/adapter-next` v0.3.0 or later (and `prismic-ts-codegen` if you're using it explicitly) and regenerating your `prismicio-types.d.ts` file? (you can create then delete a tmp slice for that to happen)

Should be fixing it, but let me know if still stuck~

**Comment by andre-lergier** [comment]
Thanks, I guess the type error should be fixed now!
Why didn't it update `@slicemachine/adapter-next` to v0.3.0 with running `npm update`?

While building / running the site now, there's a new error occuring:
<img width="999" alt="image" src="https://github.com/prismicio/prismic-client/assets/9418314/538b3f3c-914b-4dcb-b2bc-b99ecc30261a">

**Comment by angeloashmore** [comment]
Hey @andre-lergier,

> Why didn't it update @slicemachine/adapter-next to v0.3.0 with running npm update?

`v0.1.3` -> `v0.3.0` is technically a major/breaking change in SemVer — the same as going from `v1.0.0` to `v2.0.0`. `npm update` will only upgrade packages according to your `package.json` versions.

`@slicemachine/adapter-next`'s version if probably specified using the `^` symbol. `^` denotes that only minor releases are updated with `npm update`, not major releases. For example, `v0.2.0` -> `v0.2.1` would be updated with `npm update`, but `v0.2.0` -> `v0.3.0` would not.

I'll bring this issue to the team working on Slice Machine so upgrades are smoother. 🙂

> While building / running the site now, there's a new error occuring: `Method expects to have requestAsyncStorage, none available`

Ah, this shouldn't be happening. That error comes from Next.js, but seems to be triggered by `<PrismicPreview>`. Could you rollback to `@prismicio/next` `v7.0.1` and let me know if that removes the error?

**Comment by angeloashmore** [comment]
I’m going to close this issue since it should be fixed, but please let us know if it isn’t and we will re-open it. Thank you!

**Comment by andre-lergier** [comment]
Thank you, @angeloashmore.

> I'll bring this issue to the team working on Slice Machine so upgrades are smoother. 🙂

This would be great! But am I right that there is currently no site where I can find all updates with their most important changes in one place? Because I didn't find out that there's an update to `@slicemachine/adapter-next` `v0.3.0` available.

Updating `@prismicio/next` to `v1.3.1` did it!
Now everything is working fine with the newest versions! 🚀

**Comment by lihbr** [comment]
> @andre-lergier This would be great! But am I right that there is currently no site where I can find all updates with their most important changes in one place? Because I didn't find out that there's an update to `@slicemachine/adapter-next` `v0.3.0` available.

We should fix this issue, but as it's a more global "thing", to be aware of package versions, I use [Version Lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) on VS Code which is amazing at highlighting those inside your `package.json`:

![image](https://github.com/prismicio/prismic-client/assets/25330882/0bf96f11-2e2e-44b3-92a8-77d46de3d31e)
